const core = {
  slug: 'gim-goa',
  name: 'Goa Institute of Management (GIM), Goa',
  short: 'GIM Goa',
  website: 'gim.ac.in',
  location: 'Poriem, Sattari, Goa - 403505',
  founded: 1993,
  founder: null,
  director: null,
  accreditations: ['AMBA (UK)', 'SAQS', 'BGA', 'NBA (PGDM + HCM)', 'AACSB Member', 'AICTE Approved'],
  campusLabel: 'Poriem, Sattari · 50 acre residential campus · 100km from Panaji',
  color: '#0D6E4F',
  emoji: '🌴',
  tagline: "One of India's oldest private B-schools with 4 specialised PGDM tracks (General · Healthcare · Big Data Analytics · BIFS), AMBA (UK) accreditation, and a unique Portugal dual-degree for analytics. NIRF #43 · Avg ₹15.13 LPA · CAT 88%ile cutoff makes it accessible at the 85-90 percentile range.",
  nirf: 43,
  qs: null,
  ft: null,
  bt: 24,

  stats: [
    { label: 'Avg Package',     value: '₹15.13 LPA', sub: 'PGDM 2025 · Shiksha verified' },
    { label: 'Median Package',  value: '₹15 LPA',    sub: 'PGDM 2025 official' },
    { label: 'Highest Package', value: '₹32.2 LPA',  sub: 'PGDM BDA 2025' },
    { label: 'Total Fees',      value: '~₹21.7 L',   sub: 'PGDM · includes one-time fee' },
    { label: 'CAT Cutoff',      value: '88%ile',     sub: 'general category minimum' },
    { label: 'Recruiters',      value: '200+',       sub: 'companies across programmes' },
  ],

  rankings: [
    { source: 'NIRF 2025',       rank: '43rd',  note: 'Management category' },
    { source: 'NIRF 2024',       rank: '37th',  note: 'slipped 6 positions in 2025' },
    { source: 'Business Today 2024', rank: '24th', note: 'MBA category · top 25 nationally' },
    { source: 'NIRF Goa',        rank: '1st',   note: 'Best NIRF-ranked B-school in Goa' },
  ],

  programs: [
    {
      name: 'PGDM (General)',
      duration: '2 years · 6 trimesters',
      seats: 300,
      fees: '~₹21.7 L',
      intake: 'June',
      exam: 'CAT · XAT · CMAT · GMAT',
      note: 'Flagship programme · NBA accredited · AIU recognised as MBA-equivalent',
    },
    {
      name: 'PGDM — Healthcare Management (HCM)',
      duration: '2 years · 6 trimesters',
      seats: 120,
      fees: '~₹21.7 L',
      intake: 'June',
      exam: 'CAT · XAT · CMAT',
      note: 'India\'s first dedicated HCM programme · NBA accredited · 100% placement 2025',
    },
    {
      name: 'PGDM — Big Data Analytics (BDA)',
      duration: '2 years · 6 trimesters',
      seats: 180,
      fees: '~₹21.7 L',
      intake: 'June',
      exam: 'CAT · XAT · CMAT + GAAT',
      note: 'SAS, Azure, Power BI, Tableau labs · highest package ₹32.2 LPA 2025',
    },
    {
      name: 'PGDM — BIFS',
      duration: '2 years · 6 trimesters',
      seats: 120,
      fees: '~₹21.7 L',
      intake: 'June',
      exam: 'CAT · XAT · CMAT',
      note: 'Banking, Insurance & Financial Services · 99% placement · JP Morgan, Goldman Sachs, HSBC',
    },
    {
      name: 'IDA — Intl Double Degree (PGDM BDA + Nova Portugal)',
      duration: '2 years · GIM + Nova School Portugal',
      seats: 30,
      fees: 'On request',
      intake: 'June',
      exam: 'CAT · XAT · CMAT + GAAT',
      note: 'PGDM BDA (GIM) + Masters in Business Analytics (Nova, Lisbon) · global credential',
    },
    {
      name: 'Hybrid PGDM',
      duration: '2 years',
      seats: null,
      fees: '₹5.1 L',
      intake: 'Rolling',
      exam: 'Merit + PI · 3+ yrs work exp',
      note: 'Online/hybrid mode · AICTE-approved · for working professionals',
    },
    {
      name: 'FPM (Fellowship in Management)',
      duration: '4-5 years',
      seats: 10,
      fees: '₹40,000',
      intake: 'July',
      exam: 'SoP + research proposal + PI',
      note: 'Doctoral research programme · stipend available · academia-focused',
    },
  ],
}

export default core
