const core = {
  slug: 'tapmi-manipal',
  name: 'T. A. Pai Management Institute (TAPMI)',
  short: 'TAPMI',
  website: 'tapmi.edu.in',
  location: '44-acre Campus, Manipal, Udupi District, Karnataka - 576104',
  founded: 1980,
  founder: 'Late Shri Tonse Ananth Pai (Padma Bhushan)',
  director: 'Prof. Rajeev Kumra',
  accreditations: ['AACSB (US)', 'AMBA (UK)', 'AICTE Approved'],
  campusLabel: '44 acres · Beach town of Udupi-Manipal · MAHE Institution of Eminence',
  color: '#8B1A1A',
  emoji: '🌊',
  tagline: "India's leading MBA for BFSI and finance — TAPMI's MBA-BKFS is one of the few programmes in India co-designed with Bloomberg and SBI. A constituent unit of MAHE (Institution of Eminence), TAPMI holds the rare AACSB + AMBA Double Crown from a 44-acre campus in the beach town of Udupi-Manipal.",
  nirf: 39,
  qs: null,
  ft: null,
  bt: 21,

  stats: [
    { label: 'Highest Package',    value: '₹32.77 LPA', sub: 'MBA General 2025' },
    { label: 'Avg Package',        value: '₹13.99 LPA', sub: 'MBA General 2025' },
    { label: 'Top 50 Avg',         value: '₹19.16 LPA', sub: 'top 50 students 2024-25' },
    { label: 'Total Fees',         value: '₹19.50 L',   sub: 'tuition only · 2 years' },
    { label: 'CAT Cutoff',         value: '90%ile',      sub: 'freshers · general category' },
    { label: 'Alumni Network',     value: '7,000+',      sub: '42 years · global network' },
  ],

  rankings: [
    { source: 'NIRF 2025',         rank: '39th',  note: 'Management Category' },
    { source: 'Outlook-ICARE 2024',rank: '4th',   note: 'MBA (Private) Category' },
    { source: 'Business Today 2023',rank: '21st', note: 'Management Institutes' },
    { source: 'Times 2025',        rank: '30th',  note: 'Management Institutes' },
    { source: 'NIRF Karnataka',    rank: '2nd',   note: 'Best NIRF-ranked private B-school in Karnataka' },
  ],

  programs: [
    {
      name: 'MBA (General)',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT 2025 · XAT 2026 · GMAT · NMAT',
      note: 'Freshers: >90%ile · 12-23 months exp: >80%ile · 24+ months: profile-based',
    },
    {
      name: 'MBA-BKFS',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L + ₹70K training',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Banking, Finance & Financial Services · Bloomberg Lab · SBI & BSE training · highest avg ₹14.73 LPA',
    },
    {
      name: 'MBA-HRM',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Human Resource Management · avg ₹12.86 LPA · highest ₹19.59 LPA (2025)',
    },
    {
      name: 'MBA-IB',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'International Business · highest ₹16 LPA (2025)',
    },
    {
      name: 'MBA-Marketing',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Marketing · avg ₹13.72 LPA · highest ₹19.59 LPA (2025)',
    },
    {
      name: 'MBA-Tech',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Technology Management · TAPMI Bengaluru campus · >85%ile cutoff',
    },
    {
      name: 'MBA-AI & DS',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '₹19.50 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'AI & Data Science · co-taught with MSIS · Python, R, Tableau, Power BI, Cloud',
    },
  ],
}

export default core
