const core = {
  slug: 'great-lakes-chennai',
  name: 'Great Lakes Institute of Management, Chennai',
  short: 'GLIM Chennai',
  website: 'greatlakes.edu.in',
  location: 'Dr. Bala V. Balachandran Campus, ECR Road, Chengalpattu District, Tamil Nadu - 603102',
  founded: 2004,
  founder: 'Late Dr. Bala V. Balachandran (Padma Shri)',
  director: 'Dr. Debashis Sanyal',
  accreditations: ['AACSB (US)', 'AMBA (UK)', 'SAQS', 'NBA Tier 1', 'AICTE Approved'],
  campusLabel: '32 acres · LEED Platinum · ECR Road, Chengalpattu, Tamil Nadu',
  color: '#0057A8',
  emoji: '🌊',
  tagline: "South India's top MBA for analytics and consulting. GLIM Chennai holds the rare AACSB + AMBA Double Crown — one of very few Indian B-schools with both — backed by strong BFSI, consulting and analytics placements from a LEED Platinum campus 40 km from Chennai.",
  nirf: 37,
  qs: null,
  ft: null,
  bt: null,

  stats: [
    { label: 'Avg Package (PGPM)', value: '₹17.80 LPA', sub: 'PGPM 2025 report' },
    { label: 'Avg Package (PGDM)', value: '₹15 LPA',    sub: 'PGDM 2025 report' },
    { label: 'Highest (PGDM)',     value: '₹39.30 LPA', sub: 'Highest domestic 2025' },
    { label: 'PGDM Total Fees',    value: '₹22.50 L',   sub: 'all-in incl. hostel 2026-28' },
    { label: 'CAT Cutoff',         value: '85%ile',      sub: 'general category minimum' },
    { label: 'PGDM Batch 2025-27', value: '368',         sub: '35% female · 66% freshers' },
  ],

  rankings: [
    { source: 'NIRF 2025',         rank: '37th',            note: 'Management Category' },
    { source: 'Outlook 2024',      rank: '3rd',             note: 'Top Standalone Institutions' },
    { source: 'Analytics India',   rank: '5th',             note: 'Analytics B-Schools' },
    { source: 'Business Standard', rank: 'Super League 2',  note: 'Top Indian B-Schools' },
  ],

  programs: [
    {
      name: 'PGDM',
      duration: '2 years · 6 terms',
      seats: 368,
      fees: '₹22.50 L',
      intake: 'June',
      exam: 'CAT 2024/25 · XAT 2025/26 · GMAT 2023+',
      note: 'Freshers & <36 months exp · 60% throughout required',
    },
    {
      name: 'PGPM (General)',
      duration: '1 year · 7 terms',
      seats: 120,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT 2023+',
      note: '2+ years exp by 30 Apr 2026 · 1 recommendation required',
    },
    {
      name: 'PGPM — Finance',
      duration: '1 year',
      seats: null,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Derivatives, Fixed Income, FinTech, FM Lab',
    },
    {
      name: 'PGPM — Analytics',
      duration: '1 year',
      seats: null,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Predictive Modelling, Time Series, Big Data, Pricing Analytics',
    },
    {
      name: 'PGPM — Consulting',
      duration: '1 year',
      seats: null,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'Management Consulting, Digital Transformation, Execution Excellence',
    },
    {
      name: 'PGPM — Data Science',
      duration: '1 year',
      seats: null,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'NLP, Computer Vision, GenAI Models Lab, Big Data Technologies',
    },
    {
      name: 'PGPM — Product Mgmt',
      duration: '1 year',
      seats: null,
      fees: '₹23.50 L',
      intake: 'April',
      exam: 'CAT · XAT · GMAT · NMAT',
      note: 'AI for PMs, Product Lab, Stakeholder Management, Tech Product Sales',
    },
  ],
}

export default core
