const core = {
  slug: 'imt-ghaziabad',
  name: 'Institute of Management Technology (IMT), Ghaziabad',
  short: 'IMT Ghaziabad',
  website: 'imt.edu',
  location: 'Raj Nagar, Post Box No. 137, Ghaziabad, Delhi NCR - 201001',
  founded: 1980,
  founder: null,
  director: 'Dr. Atish Chattopadhyay',
  accreditations: ['AACSB (US)', 'AICTE Approved'],
  campusLabel: 'Ghaziabad, Delhi NCR · 5 mins from metro · Residential campus',
  color: '#1B4F8A',
  emoji: '🏛️',
  tagline: "One of India's oldest and largest private B-schools — IMT Ghaziabad's Delhi NCR location, AACSB accreditation, and strong BFSI/FMCG recruiter network make it a top choice at the 90-93 percentile CAT range. Avg ₹18.15 LPA with 160+ companies.",
  nirf: 35,
  qs: 151,
  ft: null,
  bt: null,

  stats: [
    { label: 'Avg Package',     value: '₹18.15 LPA', sub: 'PGDM 2025 · official report' },
    { label: 'Median Package',  value: '₹17 LPA',    sub: 'PGDM 2025 official' },
    { label: 'Highest Domestic',value: '₹35 LPA',    sub: 'domestic 2025' },
    { label: 'Total Fees',      value: '~₹21.5 L',   sub: 'PGDM tuition + one-time' },
    { label: 'CAT Cutoff',      value: '90%ile',      sub: 'general category minimum' },
    { label: 'Recruiters',      value: '160+',        sub: 'companies 2025' },
  ],

  rankings: [
    { source: 'NIRF 2025',     rank: '35th',  note: 'Management Category' },
    { source: 'QS 2025',       rank: '#151+', note: 'World Business Masters — Management' },
    { source: 'NIRF Karnataka', rank: '3rd',  note: 'Best NIRF-ranked college in Uttar Pradesh' },
  ],

  programs: [
    {
      name: 'PGDM (General)',
      duration: '2 years · 6 trimesters',
      seats: 480,
      fees: '~₹21.5 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT 650+',
      note: 'Flagship programme · 50% aggregate in graduation · Residential mandatory',
    },
    {
      name: 'PGDM — Marketing',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '~₹21.5 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT',
      note: 'Marketing specialisation · India\'s largest marketing campus competition (Marketing World Cup)',
    },
    {
      name: 'PGDM — Financial Management',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '~₹21.5 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT',
      note: 'Finance specialisation · strong BFSI placements (Goldman Sachs, D.E. Shaw, BlackRock)',
    },
    {
      name: 'PGDM — BFS',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '~₹21.5 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT',
      note: 'Banking & Financial Services · BFSI-focused track',
    },
    {
      name: 'PGDM — DCP',
      duration: '2 years · 6 trimesters',
      seats: null,
      fees: '~₹21.5 L',
      intake: 'June',
      exam: 'CAT · XAT · GMAT',
      note: 'Dual Country Programme · global exposure · international immersion built-in',
    },
    {
      name: 'Executive PGDM',
      duration: '1 year',
      seats: null,
      fees: 'On request',
      intake: 'April',
      exam: 'GMAT / work experience based',
      note: 'For working professionals · 5+ years experience preferred',
    },
  ],
}

export default core
